name: Dependency Graph

on:
  push:
    branches: [ "master", "main" ]

permissions:
  contents: write

jobs:
  dependency-submission:
    name: Submit Dependency Graph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Submit Dependency Graph
        uses: github/rust-dependency-submission-action@v1
